/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-08-24 08:00:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<script src=\"../js/jquery-3.6.0.js\"></script> <!--제이쿼리라이브러리-->\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("	        $(\"#join\").css({\r\n");
      out.write("	        	\"padding-left\":\"30px\",\r\n");
      out.write("	        	\"padding-bottom\":\"30px\",\r\n");
      out.write("	        	\"border\":\"1px solid skyblue\"\r\n");
      out.write("	        })\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"join\">\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <b><font size=\"6\" color=\"gray\">회원가입</font></b>\r\n");
      out.write("        <br><br><br>\r\n");
      out.write("        \r\n");
      out.write("        <form>\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"title\">아이디</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"text\" name=\"id\" maxlength=\"20\">\r\n");
      out.write("                        <input type=\"button\" value=\"중복확인\" >    \r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                        \r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"title\">비밀번호</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"password\" name=\"password\" maxlength=\"15\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                \r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"title\">비밀번호 확인</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"password\" name=\"password\" maxlength=\"15\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                    \r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"title\">이름</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"text\" name=\"name\" maxlength=\"40\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                    \r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"title\">성별</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"radio\" name=\"gender\" value=\"남\" checked>남\r\n");
      out.write("                        <input type=\"radio\" name=\"gender\" value=\"여\" checked>여\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                    \r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"title\">생일</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"text\" name=\"birth_yy\" maxlength=\"4\" placeholder=\"년(4자)\" size=\"6\" >\r\n");
      out.write("                        <select name=\"birth_mm\">\r\n");
      out.write("                            <option value=\"\">월</option>\r\n");
      out.write("                            <option value=\"01\" >1</option>\r\n");
      out.write("                            <option value=\"02\" >2</option>\r\n");
      out.write("                            <option value=\"03\" >3</option>\r\n");
      out.write("                            <option value=\"04\" >4</option>\r\n");
      out.write("                            <option value=\"05\" >5</option>\r\n");
      out.write("                            <option value=\"06\" >6</option>\r\n");
      out.write("                            <option value=\"07\" >7</option>\r\n");
      out.write("                            <option value=\"08\" >8</option>\r\n");
      out.write("                            <option value=\"09\" >9</option>\r\n");
      out.write("                            <option value=\"10\" >10</option>\r\n");
      out.write("                            <option value=\"11\" >11</option>\r\n");
      out.write("                            <option value=\"12\" >12</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <input type=\"text\" name=\"birth_dd\" maxlength=\"2\" placeholder=\"일\" size=\"4\" >\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                    \r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"title\">이메일</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"text\" name=\"email_1\" maxlength=\"30\">@\r\n");
      out.write("                        <select name=\"email_2\">\r\n");
      out.write("                            <option>naver.com</option>\r\n");
      out.write("                            <option>daum.net</option>\r\n");
      out.write("                            <option>gmail.com</option>\r\n");
      out.write("                            <option>nate.com</option>                        \r\n");
      out.write("                        </select>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                    \r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"title\">휴대전화</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"text\" name=\"phone\" />\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td id=\"title\">주소</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"text\" size=\"50\" name=\"address\"/>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <br>\r\n");
      out.write("            <input type=\"submit\" value=\"가입\"/>  <input type=\"button\" value=\"취소\">\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
